name: Deploy Bulker to Wasmer

on:
  workflow_dispatch:
    inputs:
      org_id:
        description: 'Organization ID for deployment'
        required: true
        type: string
      data:
        description: 'Data to send to Bulker'
        required: true
        type: string
      sync_id:
        description: 'Data to send to Bulker'
        required: true
        type: string


env:
  GO_VERSION: '1.21'
  WASMER_VERSION: '4.2.5'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@v3.1
        with:
          version: ${{ env.WASMER_VERSION }}

      - name: Build Bulker Binary
        run: |
          go mod download
          GOOS=js GOARCH=wasm go build -o bulker.wasm

      - name: Deploy to Wasmer
        env:
          WASMER_TOKEN: ${{ secrets.WASMER_TOKEN }}
          # Bulker Environment Variables
          BULKER_INSTANCE_ID: ${{ github.event.inputs.sync_id }}
          BULKER_HTTP_PORT: '3042'
          BULKER_AUTH_TOKENS: ${{ secrets.BULKER_CONFIG_SOURCE_HTTP_AUTH_TOKEN }}
          BULKER_KAFKA_BOOTSTRAP_SERVERS: ${{ secrets.BULKER_KAFKA_BOOTSTRAP_SERVERS }}
          BULKER_KAFKA_SSL: 'true'
          BULKER_KAFKA_SSL_SKIP_VERIFY: 'true'
          BULKER_KAFKA_TOPIC_PREFIX: ${{ github.event.inputs.org_id }}
          # Optional ClickHouse Events Log
          BULKER_CLICKHOUSE_HOST: ${{ secrets.BULKER_CLICKHOUSE_HOST }}
          BULKER_CLICKHOUSE_DATABASE: ${{ secrets.BULKER_CLICKHOUSE_DATABASE }}
          BULKER_CLICKHOUSE_SSL: 'true'
          BULKER_CLICKHOUSE_USERNAME: ${{ secrets.BULKER_CLICKHOUSE_USERNAME }}
          BULKER_CLICKHOUSE_PASSWORD: ${{ secrets.BULKER_CLICKHOUSE_PASSWORD }}
        run: |
          # Create Wasmer package manifest
          cat > wapm.toml << EOF
          [package]
          name = "bulker"
          version = "1.0.0"
          description = "Bulker server for data processing"

          [[module]]
          name = "bulker"
          source = "bulker.wasm"
          abi = "wasi"

          [module.interfaces]
          wasi = "0.1.0"
          EOF
          
          # Login to Wasmer
          wasmer login --token "$WASMER_TOKEN"
          
          # Package and publish
          wasmer publish

      - name: Verify Deployment
        run: |
          wasmer run bulker --env-file <(cat << EOF
          BULKER_INSTANCE_ID=${BULKER_INSTANCE_ID}
          BULKER_HTTP_PORT=3042
          # ... other environment variables ...
          EOF
          )