name: Deploy Bulker

on:
  workflow_dispatch:
    inputs:
      org_id:
        description: 'Org ID to fetch configuration'
        required: true
      data:
        description: 'Data to send to Bulker'
        required: true    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_TOKEN }}"
          github_token: "${{ secrets.REPO_TOKEN }}"

      - name: Build and deploy Bulker to Koyeb
        id: deploy_bulker
        env:
          BULKER_BATCH_RUNNER_DEFAULT_BATCH_SIZE: '10000'
          BULKER_BATCH_RUNNER_DEFAULT_PERIOD_SEC: '300'
          BULKER_CONFIG_SOURCE: ${{ secrets.BULKER_CONFIG_SOURCE }}
          BULKER_CONFIG_SOURCE_HTTP_AUTH_TOKEN: ${{ secrets.BULKER_CONFIG_SOURCE_HTTP_AUTH_TOKEN }}
          BULKER_KAFKA_BOOTSTRAP_SERVERS: ${{ env.BULKER_KAFKA_BOOTSTRAP_SERVERS }}
          BULKER_KAFKA_SSL: 'true'
          BULKER_CLICKHOUSE_HOST: ${{ env.BULKER_CLICKHOUSE_HOST }}
          BULKER_CLICKHOUSE_DATABASE: ${{ env.BULKER_CLICKHOUSE_DATABASE }}
          BULKER_CLICKHOUSE_SSL: 'true'
          BULKER_CLICKHOUSE_USERNAME: ${{ env.BULKER_CLICKHOUSE_USERNAME }}
          BULKER_CLICKHOUSE_PASSWORD: ${{ secrets.BULKER_CLICKHOUSE_PASSWORD }}
          BULKER_KAFKA_TOPIC_PREFIX: ${{ github.event.inputs.org_id }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: koyeb service redeploy ${{ github.event.inputs.org_id }}/bulker --image jitsucom/bulker:latest --env-file .env

      - name: Output deployment status
        run: echo "Bulker deployed successfully for customer: ${{ github.event.inputs.org_id }}"